### ISSUE TITLE
`0 */ * * *` is considered valid

### ISSUE THREAD

**Issue by oliverwoodings** [TheCloudConnectors/cron-validator#1]
First of all, thanks for the great light-weight validation library! All others out there are super heavy and have dependencies on libraries like moment.

I have come across a small bug. The string `0 */ * * *` is considered a valid crontab according to this library. Crontab.guru reports it as invalid, and other cron libraries are also blowing up with that string:

![Screenshot 2019-11-04 at 15 26 21](https://user-images.githubusercontent.com/621323/68132957-78f28080-ff17-11e9-8a66-c34901194333.png)

![Screenshot 2019-11-04 at 15 27 12](https://user-images.githubusercontent.com/621323/68133037-9aec0300-ff17-11e9-8211-b699556589d0.png)

**Comment by GuillaumeRochat** [comment]
Oh wow, I really dropped the ball on this one. Thanks for the bug report! :) I added some other tests to ensure ranges don't have the same issue.

**Comment by oliverwoodings** [comment]
Amazing turnaround, thanks!
