### ISSUE TITLE
Does not support upper and lower letters ?

### ISSUE THREAD

**Issue by aloehh** [TheCloudConnectors/cron-validator#19]
Does not support upper and lower letters : ' 0 15 10 L * ?'

**Comment by GuillaumeRochat** [comment]
This feature is supported by this other library : https://github.com/Airfooox/cron-validate

**Comment by GuillaumeRochat** [comment]
I will not add this feature as it is available in https://github.com/Airfooox/cron-validate and do not want to recreate the feature.
