### ISSUE TITLE
Warning via loading sourcemaps via source-map-loader for webpack

### ISSUE THREAD

**Issue by gdbd** [TheCloudConnectors/cron-validator#20]
Hello, durring build in our project there is in output:

```WARNING in ./node_modules/cron-validator/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/run/media/denis/data_lin/
code/project/node_modules/cron-validator/src/index.ts' file: 

Error: ENOENT: no such file or directory, open '/run/media/denis/data_lin/
code/project/node_modules/cron-validator/src/index.ts'
```

i am found npm package (version 1.2.1) contains index.js.map whisch referes `../src/index.ts` not existing in project

Can this be fixed in the package?

**Comment by ltruchot** [comment]
Thank you very much for the high quality work done here, everyone.

Issue is very easy to reproduce with CRA, that use webpack under the hood:
```sh
npx create-react-app test-cron-validator --template typescript
cd test-cron-validator    
npm install cron-validator 
npm start
```
will show the error

We can see here the root of the problem: https://npm.runkit.com/cron-validator/lib/index.js.map?t=1642434751629
`"sources":["../src/index.ts"]` in a published build without "./src" folder, as discovered by @gdbd

**Comment by ltruchot** [comment]
The recommended way to go in TS libs (if we don't want to publish the `src` folder), is to simply add: `"inlineSources": true` in `compilerOptions` of tsconfig.json.
@see https://www.typescriptlang.org/tsconfig#inlineSources
@see https://www.carlrippon.com/emitting-typescript-source-maps/
I will do a PR about that, thank you @gdbd and @GuillaumeRochat

**Comment by ltruchot** [comment]
Job done, hope you'll have an occasion to re-publish to 1.2.2, @GuillaumeRochat, I use you good work in production !

**Comment by GuillaumeRochat** [comment]
@ltruchot thanks for the PR, I'll check it out this week, I'm due for an update/cleanup.

**Comment by GuillaumeRochat** [comment]
@gdbd @ltruchot I published 1.3.0. Can you confirm that it fixes this issue?

**Comment by ltruchot** [comment]
@GuillaumeRochat it work like a charm, thank you so much !

**Comment by gdbd** [comment]
@GuillaumeRochat, @ltruchot  yes it is fixed now,  thanks for the quick response and fix!
