### ISSUE TITLE
Year field not supported

### ISSUE THREAD

**Issue by Airfooox** [TheCloudConnectors/cron-validator#8]
Hey,
I'm using this library to validate user inputted cron's. Im trying to validate cron's like:
`0 0 * * * ? *`

As you can see, there are 7 fields in this cron:
- seconds,
- minutes,
- hours,
- days of month,
- month,
- days of week,
- year.

When validating such crons, the library returns, that they are invalid, even though they are not. Would be nice to add compatibility with the year field, thanks! :D

**Comment by GuillaumeRochat** [comment]
Thanks for filling the issue. 

We do plan to support years eventually (alongside AWS more strict cron expressions for their cloudwatch events). I can't offer any ETA however.

Contributions are welcomed to support this.

**Comment by GuillaumeRochat** [comment]
Closing this in favor of https://github.com/Airfooox/cron-validate that supports the year and has a nice preset function. This will keep this lib leaner.
